import { useState, useMemo } from 'react'
import { Link } from 'react-router-dom'
import { useQuery } from '@tanstack/react-query'
import { ShieldAlert, Search, ArrowRight, AlertTriangle } from 'lucide-react'
import { listEntities, listRiskAssessments } from '@/api/entities'
import { listSignals } from '@/api/signals'
import { Skeleton, ErrorState, EmptyState } from '@/components/feedback/States'

export function UserRiskPage() {
  const [searchTerm, setSearchTerm] = useState('')
  const [tierFilter, setTierFilter] = useState('ALL')

  const { data: riskData, isLoading: riskLoading, error: riskError, refetch } = useQuery({
    queryKey: ['user-risk-assessments-list', tierFilter],
    queryFn: () =>
      listRiskAssessments({
        limit: 50,
        rating: tierFilter !== 'ALL' ? tierFilter : undefined,
      }),
  })

  const { data: entitiesData, isLoading: entitiesLoading } = useQuery({
    queryKey: ['user-risk-entities-list'],
    queryFn: () => listEntities({ limit: 100 }),
  })

  const { data: signalsData } = useQuery({
    queryKey: ['user-risk-signals-list'],
    queryFn: () => listSignals({ limit: 100 }),
  })

  const entities = entitiesData?.properties || entitiesData?.items || []
  const signals = signalsData?.items || (signalsData as any)?.signals || []
  const riskAssessments = riskData?.items || []

  // Entity lookup map
  const entitiesMap = useMemo(() => {
    const map = new Map<string, (typeof entities)[0]>()
    entities.forEach((e) => map.set(e.property_id, e))
    return map
  }, [entities])

  // Signals lookup map
  const signalsMap = useMemo(() => {
    const map = new Map<string, typeof signals>()
    signals.forEach((s) => {
      const existing = map.get(s.entity_id) || []
      existing.push(s)
      map.set(s.entity_id, existing)
    })
    return map
  }, [signals])

  const riskCards = useMemo(() => {
    return riskAssessments.map((r) => {
      const entity = entitiesMap.get(r.entity_id)
      const entitySignals = signalsMap.get(r.entity_id) || []
      const rating = (r.overall_rating || 'UNRATED').toUpperCase()

      return {
        assessment: r,
        entityId: r.entity_id,
        canonicalName: entity?.canonical_name || `Entity ${r.entity_id}`,
        sector: entity?.sector || 'Unassigned',
        region: entity?.region || 'Unspecified',
        rating,
        signalsCount: entitySignals.length,
        primarySignals: entitySignals.slice(0, 2),
      }
    })
  }, [riskAssessments, entitiesMap, signalsMap])

  const filteredCards = useMemo(() => {
    return riskCards.filter((card) => {
      if (!searchTerm) return true
      const q = searchTerm.toLowerCase()
      return (
        card.canonicalName.toLowerCase().includes(q) ||
        card.entityId.toLowerCase().includes(q) ||
        card.sector.toLowerCase().includes(q)
      )
    })
  }, [riskCards, searchTerm])

  const isLoading = riskLoading || entitiesLoading

  return (
    <div className="space-y-6">
      {/* Title & Subtitle */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-hairline pb-4">
        <div>
          <h1 className="text-2xl font-display font-medium text-strong">Risk Intelligence</h1>
          <p className="text-xs sm:text-sm text-muted">Review risk assessments generated by ECHO.</p>
        </div>
      </div>

      {/* Filter and Search */}
      <div className="flex flex-col sm:flex-row gap-3">
        <div className="relative flex-1">
          <input
            type="text"
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            placeholder="Search risk by entity name, ID, or sector..."
            className="min-h-10 w-full border border-hairline bg-surface px-3 pl-9 text-xs text-ink placeholder:text-muted/60 focus:border-signal focus:outline-none font-mono"
          />
          <Search size={14} className="text-muted absolute left-3 top-3" />
        </div>

        <div className="flex flex-wrap gap-1.5 font-mono text-[10px] uppercase">
          {['ALL', 'CRITICAL', 'HIGH', 'MEDIUM', 'LOW'].map((tier) => (
            <button
              key={tier}
              type="button"
              onClick={() => setTierFilter(tier)}
              className={`px-3 py-2 border transition-colors ${
                tierFilter === tier
                  ? 'border-signal bg-signal/15 text-strong font-semibold'
                  : 'border-hairline bg-surface text-muted hover:text-strong'
              }`}
            >
              {tier}
            </button>
          ))}
        </div>
      </div>

      {/* Risk Cards */}
      {isLoading ? (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <Skeleton className="h-44 w-full" />
          <Skeleton className="h-44 w-full" />
          <Skeleton className="h-44 w-full" />
          <Skeleton className="h-44 w-full" />
        </div>
      ) : riskError ? (
        <ErrorState message="Could not load risk assessments from database." onRetry={refetch} />
      ) : filteredCards.length === 0 ? (
        <EmptyState
          title="No Risk Assessments Found"
          message="No corporate entity risk assessments match the selected filter."
        />
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {filteredCards.map(({ assessment, entityId, canonicalName, sector, region, rating, signalsCount, primarySignals }) => (
            <div
              key={assessment.assessment_id || entityId}
              className="border border-hairline bg-surface p-5 hover:border-signal/40 transition-colors flex flex-col justify-between space-y-4"
            >
              <div className="space-y-2">
                <div className="flex items-center justify-between">
                  <span className="font-mono text-xs text-signal font-semibold">
                    {entityId}
                  </span>
                  <span
                    className={`font-mono text-[10px] uppercase px-2 py-0.5 border font-semibold ${
                      rating === 'CRITICAL'
                        ? 'border-loss bg-loss/15 text-loss'
                        : rating === 'HIGH'
                        ? 'border-amber-500/40 bg-amber-500/10 text-amber-500'
                        : 'border-hairline bg-surface-2 text-muted'
                    }`}
                  >
                    [{rating}]
                  </span>
                </div>

                <div>
                  <h3 className="text-base font-medium text-strong font-sans">
                    {canonicalName}
                  </h3>
                  <p className="text-[11px] font-mono text-muted">
                    {sector} &bull; {region}
                  </p>
                </div>

                {/* Primary indicators & Supporting Signals */}
                <div className="space-y-1.5 pt-2 border-t border-hairline font-mono text-xs">
                  <p className="text-[10px] uppercase tracking-wider text-muted font-semibold">
                    Supporting Signals ({signalsCount})
                  </p>
                  {primarySignals.length > 0 ? (
                    <ul className="space-y-1">
                      {primarySignals.map((s: any) => (
                        <li key={s.signal_id} className="text-ink text-[11px] truncate flex items-center gap-1.5">
                          <span className="h-1.5 w-1.5 rounded-full bg-signal shrink-0" />
                          <span>{s.description || s.title || s.signal_id}</span>
                        </li>
                      ))}
                    </ul>
                  ) : (
                    <p className="text-[11px] text-muted">No acute disclosure contradictions flagged.</p>
                  )}
                </div>
              </div>

              <div className="pt-3 border-t border-hairline flex items-center justify-end">
                <Link
                  to={`/app/risk/${entityId}`}
                  className="inline-flex items-center gap-1.5 border border-signal bg-signal/15 px-3.5 py-1.5 text-xs font-mono text-strong uppercase tracking-wider font-semibold hover:bg-signal/25 transition-colors"
                >
                  <span>View Assessment</span>
                  <ArrowRight size={13} className="text-signal" />
                </Link>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  )
}
